services:
  webserver:
    build: ./.docker/server_1/
    ports:
      - ${PORT}:80
    image: blog_ssrf_without_hue
    networks:
      my_ssrf_network:
        ipv4_address: 172.20.0.11
  webserver2:
    build: ./.docker/server_2/
    image: light_ssrf_without_hue
    command: npm start
    networks:
      my_ssrf_network:
        ipv4_address: 172.20.0.12
networks:
  my_ssrf_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
